### PR TITLE
fillstruct add go modules support

### PR DESCRIPTION
**Pull request by anjmao**

### CODE REVIEW

**Comment by anjmao** [comment]
Hi, I converted fillstruct to work with go modules. The only part I didn't covered is modified flag which is I'm not sure how to convert it to go modules.

**Comment by davidrjenni** [comment]
Thank you @anjmao for this PR. I think the changes are fine, but we also need the `-modified` flag working, because editor plugins like `vim-go` use this in order to correctly handle buffers or modified files that are not yet written to disk.

I think you could implement it by using [buildutil.ParseOverlayArchive](https://godoc.org/golang.org/x/tools/go/buildutil#ParseOverlayArchive) similar to [gogetdoc](https://github.com/zmb3/gogetdoc/blob/master/main.go#L82).

What do you think?

**Comment by anjmao** [comment]
@davidrjenni Thanks, I will use ParseOverlayArchive and update my PR.

**Comment by davidrjenni** [comment]
Thank you @anjmao.

Only one thing: are you sure the `go.{mod,sum}` files are correct?
The only two dependencies for this repo I see are `github.com/kisielk/gotool` and `golang.org/x/tools`. If I run `go mod init` these two are added to the `go.{mod,sum}`.

**Comment by anjmao** [comment]
I updated go.mod with missing github.com/kisielk/gotool, since I was not building other folders it probably didn't added it. go.sum file includes protobuf and appengine since they are in on x/tools, at least appengine is used in playground.go, for protobuf I see it included on tools go.sum file https://github.com/golang/tools/blob/97f80cd5504df5e234a0ce7ba9a0f412468307fb/go.sum#L1

**Comment by davidrjenni** [comment]
Sorry for the slow response and thank you again for the PR.

Could you update the dependencies (`go get -u ./... && go mod tidy`) once again and then update the vendor directory (`go mod vendor`)?

Thank you.

**Comment by rudle** [comment]
Any movement here? I'm eager to use `fillstruct` with go modules. Thanks!

**Comment by anjmao** [comment]
@davidrjenni Sorry for late response. I updated modules and vendor folder.

**Comment by davidrjenni** [comment]
Thank you very much @anjmao for this PR.

**Pull request merged**
